### PR TITLE
Customize prefetch

### PR DESCRIPTION
**Pull request by SyncM1972**
In a parallelized worker scenario, it is desirable to be able to control the number of prefetched messages per worker.
For this, the constant number of 50 prefetched messages can be modified by an additional prefetch_count parameter.

### CODE REVIEW

**Comment by atheriel** [comment]
Thanks, this is a nice and clear change. Can you please do the following?

1. Remove the unrelated changes to the `DESCRIPTION` and `.gitignore` files.
2. Move the `NEWS` entry into the `longears 0.2.4.9000` section (below the existing entry) and use the existing format (indented, sentence case, 80 columns).
3. Squash your changes into a single commit with a single commit message.

**Comment by SyncM1972** [comment]
Thank you for your comments.
I have performed the requested operations.

**Comment by atheriel** [comment]
The changes look good. It looks like the commit changes permissions on `cleanup` and `configure`, though, which is almost certainly a mistake.

**Comment by SyncM1972** [comment]
The permissions are corrected.

**Comment by atheriel** [comment]
I merged this manually in  606573c. Thanks!

**Pull request closed without merging**
